<script>
	import { RemoteFilter } from '$lib/remote';
</script>

<h1>Filter</h1>

<!--
    The form is connected to the remote function via {...RemoteFilter}
    This automatically:
    - handles submission
    - sends the form data to the server
    - updates the page with the returned data
-->
<form {...RemoteFilter}>
	<h3>Filter by ID</h3>
	<label>
		<!--
			Checkbox for filtering by ID
			- name="id" is generated by RemoteFilter.fields.id (the line '.fields.id' does this)
			- value="1" is sent when this checkbox is checked. the value is used when filtering
		-->
		<input {...RemoteFilter.fields.id.as('checkbox', '1')} />
		ID 1
	</label>
	<label>
		<input {...RemoteFilter.fields.id.as('checkbox', '6')} />
		ID 6
	</label>

	<h3>Filter by title</h3>
	<label>
		<!--
			Checkbox for filtering by title
			- name="title" is generated from: '.fields.title.'
			- value="Berglandschap" is sent when checked
		-->
		<input {...RemoteFilter.fields.title.as('checkbox', 'Berglandschap')} />
		Berglandschap
	</label>
	<label>
		<input {...RemoteFilter.fields.title.as('checkbox', 'Woestijnlandschap')} />
		Woestijnlandschap
	</label>

	<button>Apply</button>
</form>
<!--
    Submitting the form sends all selected checkboxes to the remote function.
    The data arrives on the server as:
    {
        id?: string[],
        title?: string[]
    }
-->
